### ISSUE TITLE
Wiki mistake?

### ISSUE THREAD

**Issue by fabolhak** [artivis/laser_odometry#26]
Hello,

thank you for this great plugin. It is very useful to compare different laser odometry approaches. One little detail: I read the wiki and stumbled upon the following:

> ~fixed_sensor (bool, default: true)
> Whether the laser sensor if fixed w.r.t the base_frame or not. In case it is set to `true`, the node tries to retrieve the sensor pose from tf prior to each odometry publication.

Shouldn't it be "In case it is set to **`false`** ... "?

Thanks.

**Comment by artivis** [comment]
Fixed, thanks :+1:
